language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
deploy:
  provider: heroku
  app: http4k-demo-s3box
  api_key:
    secure: fKjswerSg9BTx2k/HYVpEut4QlCozlCSjvvppq5QGUIRMWIDLzW13zKfajCrES7vcEHz+IVyJLUKnGi9BAnixjZLepJwc2dMLunpNKGyBlAZ0HyI5NfM+pc7yb84kIOZjwoFCy2e7P2KeYP4BszV7KSFXsuic/QtZbhuVzaT2FEKFqmzCtX1bIxobZXiLBcJ49n6gXrBg8vjXBqm58fwGEClMrxFloGPrS9SztM4/g9vj8zgeGgx/mheRl27JquM9JGwCM4kRHQvxoQNtrka2A61c5j/aVYFPXKy6LErRm8h75/8FJQWA0j3APNwsybLiMdorptGsaXHhU7SZx38gVtDBR57nJvV6++xxaXw6PEm5elRIrqdOcJjZdx+QeXawtJYC5yj5qd1M3DVXFhbZx/LVyl6qR5Ts44bVI3iBYdjggXcSBsmhkthEYmgiurq+L5hyIzc1egPQbPO6YDdThdKJJvfud9XY9mO/HC9jvJ8U6oh8q9x8zPxCm4KxqHMEdeJJSBe1pxkS24FAuFs5NRqe+QM2LrUAKQPcBk4jBRRPXiZfHiiy7i5L6oaZ8lp6XthZROflLIZdA9cqpcjvYypNWbP9Jj7mU2tL00yz7CrN9o7JhQKRNuUAyAeDzQTDaBcdQPvC8z8+42pVrU1K7WbRr3W3oIRGGINjnBL89M=
